### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by defunkt1721** [raphael/linux-4.1-samus#10]
Hi, I've installed the patched kernel on my Pixel running Antergos with Gnome and everything's awesome but the camera does not work. Is there any fix for it yet?

For anyone else who's running Antergos and has suspend trouble - change your display manager from LightDM to GnomeDM and it works like a charm! :)

Cheers! 

PS: I have an issue with Steam where I get an error saying:

 "You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6" 

I've done some searching and reading around the Arch forums but I can't get it to work. If you can shed some insight on this, it would be much appreciated.

**Comment by raphael** [comment]
Thanks for the report, I pushed a new version of the packages and source that enable the webcam and IA32.

**Comment by defunkt1721** [comment]
Awesome! I'll test it out and report :+1: 

I just need to follow the steps for installing the patched kernel again and it should overwrite the previous one, right?

Thanks for your work mate!

**Comment by raphael** [comment]
Following the same steps should overwrite the previous version. The only reason I use "should" instead of "will" is that it depends on how you update your boot loader.

**Comment by defunkt1721** [comment]
Yup, camera is working :) 

Closing this issue down
