### ISSUE TITLE
Steam Broken

### ISSUE THREAD

**Issue by nevetas** [raphael/linux-4.1-samus#11]
Saw another person mention this so thought I'd start a new topic.

If I boot into 4.1 generic steam works fine, if I boot into 4.1-samus I get the following:

"You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6"

Missing module or library path maybe?

**Comment by raphael** [comment]
I think that's because the kernel config that I used does not enable IA32 emulation. To enable it run `make nconfig` in `linux/build` and select the option `Execute file formats / Emulations -> IA32 Emulation`. You may also want to enable `x32 ABI for 64-bit mode`. Recompile, install and reboot.

**Comment by nevetas** [comment]
Thanks, will try now.

**Comment by nevetas** [comment]
Another issue solved, thanks raphael!

**Comment by raphael** [comment]
I pushed a new version that enables IA32 by default since that's something that's probably useful in a number of cases, thanks for the report!
