### ISSUE TITLE
debian binary not working

### ISSUE THREAD

**Issue by chavezmx** [raphael/linux-4.1-samus#12]
Hi,

I have tried the latest binary on debian 8, but it will not boot, after the grub screen, it freeze at loading ramdisk ...

I will try running the script to generate my on patch ...

**Comment by chavezmx** [comment]
Hi again I already compiled a 4.1 release with the script, and modified the .config to add support to lvm and swap, but again it freeze at the same point  with no output.

**Comment by mattbutlar** [comment]
I am having the same issue as I have a lvm setup.  It hangs at loading ramdisk.  Let me know if you find a solution.

**Comment by raphael** [comment]
The latest build (` linux-image-4.1.0ph+_4.1.0ph+-4_amd64.deb`)  supports LVM so if you're using that I'm not sure it's the issue. Maybe a module that is supposed to be loaded during the startup process in the initramfs is missing? what's the content of your `/etc/mkinitcpio.conf` file? or is Ubuntu using `mkinitramfs`? in which case the interesting file would be `/etc/initramfs-tools/initramfs.conf`.

**Comment by chavezmx** [comment]
I haven't tried your last build, but here is the file content in debian:

cat /etc/initramfs-tools/initramfs.conf |grep -v "#"
MODULES=most
BUSYBOX=y
KEYMAP=n
COMPRESS=gzip
DEVICE=
NFSROOT=auto

**Comment by mattbutlar** [comment]
I did try the new one because I saw the changes and it looked like lvm support was added.  This is my initramfs.

MODULES=most
BUSYBOX=y
COMPCACHE_SIZE=""
COMPRESS=gzip
BOOT=local
DEVICE=
NFSROOT=auto

**Comment by raphael** [comment]
OK one thing that might be worth trying: the kernel is built using XZ compression and not gzip as shown in the initramfs.conf.

**Comment by chavezmx** [comment]
I compiled it using gzip compression and tried again, but still not working.

**Comment by raphael** [comment]
I tried to repro using a VM but ubuntu boots just fine with "my" kernel in VirtualBox :( Could you try going through https://wiki.debian.org/InitramfsDebug? the `Rescue shell` section in particular...

**Comment by chavezmx** [comment]
Hi Raphael, today I tested the last version and it's working fine now. The problem with the sound is still there( no such device) but the kernel started correctly, thanks for the the release.

**Comment by raphael** [comment]
Could you open a new issue for the sound? also just to make sure what does `uname -r` return?

**Comment by AndreiCherniaev** [comment]
**firmware d102e_ucode.bin for driver e100 missing**

How I can fix it? Method A. Do steps:
0) My board's driver mount to my laptop on _/media/a/rootfs_
1) cd /media/a/rootfs/lib/firmware/
2) mkdir e100 
3) copy [d102e_ucode.bin](https://gitlab.freedesktop.org/frankbinns/linux-firmware/-/tree/powervr/e100) to your board's drive
sudo cp /home/a/myb/d102e_ucode.bin /media/a/rootfs/lib/firmware/
4) Now it should be work.

Or use alternative method B. Just set this:

![Screenshot from 2022-11-15 13-36-17](https://user-images.githubusercontent.com/27889022/201828397-4e450359-a395-44ec-9f29-83a318913c06.png)
