### ISSUE TITLE
Audio no working in debian 8

### ISSUE THREAD

**Issue by chavezmx** [raphael/linux-4.1-samus#13]
Hi I have been running some test in debian after installing the last version, but something seems to be missing. First I tried running the audio setup manual but the first command return the following error: 

ALSA lib main.c:273:(execute_sequence) unable to open ctl device 'hw:bdwrt5677'
ALSA lib main.c:1475:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such device

I tried to list the cards available:

 aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

check about the modules been loaded:

 lsmod | grep bdw
snd_soc_sst_bdw_rt5677_mach     7593  0 
snd_soc_sst_haswell_pcm    44737  1 snd_soc_sst_bdw_rt5677_mach
snd_soc_rt5677        163345  1 snd_soc_sst_bdw_rt5677_mach
snd_soc_core          127931  4 snd_soc_rt5677,snd_soc_rt5677_spi,snd_soc_sst_haswell_pcm,snd_soc_sst_bdw_rt5677_mach

then I got a little confused here, when I run alsaucm the card seems to be present ?

alsaucm listcards
  0: DAISY-I2S
    Daisy internal card
  1: Manta-I2S
  2: Manta-SPDIF
  3: PandaBoard
  4: PandaBoardES
  5: SDP4430
  6: Tuna
  7: apq8064-tabla-snd-card
  8: bdw-rt5677
    Samus internal card
  9: tegra-rt5640
  10: tegraalc5632

I tried openening the card conf like following: 
alsaucm open bdw-rt5677
and it shows no error

by the way the output of the script sound.sh is :

./sound.sh 
Setting sound card UCM verb
No protocol specified
xcb_connection_has_error() returned true
ALSA lib main.c:273:(execute_sequence) unable to open ctl device 'hw:bdwrt5677'
ALSA lib main.c:1475:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such device
!!Failed to set UCM verb, make sure 'alsaucm' is installed

**Comment by raphael** [comment]
What does `ls /dev/snd` return? mine is:
```
➜  linux-patched ls /dev/snd
by-path    controlC1  pcmC0D0p  pcmC0D2c  pcmC1D7p  seq
controlC0  hwC1D0     pcmC0D1c  pcmC1D3p  pcmC1D8p  timer
```
I don't think that `alsaucm` listing the card is relevant, it just means that there's a configuration for the card. Also do you seen any error in `dmesg` relating to the sound card? Do you see the following:
```
➜  linux-patched dmesg | grep bdw
[    2.297575] bdw-rt5677 bdw-rt5677: snd-soc-dummy-dai <-> System Pin mapping ok
[    2.297614] bdw-rt5677 bdw-rt5677: snd-soc-dummy-dai <-> Capture Pin mapping ok
[    2.297627] bdw-rt5677 bdw-rt5677: rt5677-dspbuffer <-> spi-RT5677AA:00 mapping ok
[    2.308083] bdw-rt5677 bdw-rt5677: rt5677-aif1 <-> snd-soc-dummy-dai mapping ok
[    2.323648] input: bdw-rt5677 Headphone Jack as /devices/pci0000:00/INT3438:00/bd
-rt5677/sound/card0/input10
[    2.323909] input: bdw-rt5677 Mic Jack as /devices/pci0000:00/INT3438:00/bdw-rt5677/sound/card0/input11
```

**Comment by chavezmx** [comment]
Here is the output ls /dev/snd/
by-path  controlC1  hwC1D0  pcmC1D3p  pcmC1D7p	pcmC1D8p  seq  timer

and dmesg:
sst-acpi INT3438:00: Cannot load firmware intel/IntcSST2.bin
bdw-rt5677 bdw-rt5677: ASoC: CPU DAI System Pin not registered
snd_soc_rt5677: unknown parameter 'index' ignored
atmel_mxt_ts i2c-ATML0000:01: Direct firmware load for maxtouch.cfg failed with error -2

**Comment by chavezmx** [comment]
Hi I tried solving the problem with this module IntcSST2.bin, I downloaded from the kernel repository and place it under /lib/firmware/intel/

Then restarted the machine I the error reported before where gone:
[    1.056393] bdw-rt5677 bdw-rt5677: snd-soc-dummy-dai <-> System Pin mapping ok
[    1.056418] bdw-rt5677 bdw-rt5677: snd-soc-dummy-dai <-> Capture Pin mapping ok
[    1.056430] bdw-rt5677 bdw-rt5677: rt5677-dspbuffer <-> spi-RT5677AA:00 mapping ok
[    1.063164] bdw-rt5677 bdw-rt5677: rt5677-aif1 <-> snd-soc-dummy-dai mapping ok

but something else failed I can see the card in alsamixer but I got :

[   13.960085] haswell-pcm-audio haswell-pcm-audio: FW loaded, mailbox readback FW info: type 01, - version: 00.00, build 77, source commit id: 876ac6906f31a43b6772b23c7c983ce9dcb18a19
[  161.145901] bdw-rt5677 bdw-rt5677: ASoC: can't get playback BE for DSP Buffer
[  161.145906]  System PCM: ASoC: no BE found for DSP Buffer
[  161.145908] bdw-rt5677 bdw-rt5677: ASoC: can't get playback BE for DSP Capture
[  161.145910]  System PCM: ASoC: no BE found for DSP Capture
[  161.168294] haswell-pcm-audio haswell-pcm-audio: FW loaded, mailbox readback FW info: type 01, - version: 00.00, build 77, source commit id: 876ac6906f31a43b6772b23c7c983ce9dcb18a19
[  209.948611] haswell-pcm-audio haswell-pcm-audio: FW loaded, mailbox readback FW info: type 01, - version: 00.00, build 77, source commit id: 876ac6906f31a43b6772b23c7c983ce9dcb18a19
[  316.561252] haswell-pcm-audio haswell-pcm-audio: FW loaded, mailbox readback FW info: type 01, - version: 00.00, build 77, source commit id: 876ac6906f31a43b6772b23c7c983ce9dcb18a19
[  316.646371] rt5677 i2c-RT5677CE:00: DSP VAD: enable=1, activity=0
[  316.658113] rt5677 i2c-RT5677CE:00: Direct firmware load for rt5677_elf_vad failed with error -2
[  316.658119] rt5677 i2c-RT5677CE:00: Request rt5677_elf_vad failed -2

**Comment by raphael** [comment]
ahah looks like you're missing the `rt566_elf_vad` firmware. It's in the `firmware` directory. The `sound.sh` script is supposed to copy it but I'm guessing firmwares are located in different places in debian and arch... Maybe you could fix the `sound.sh` script and send a PR? ;)

**Comment by chavezmx** [comment]
the script looks fine, the problem seems to be that it calls sudo, and I have no sudo, so I just removed the sudo from the script and the files were copied fine, but still no sound, now there are no problems shown in the logs just, every time I run alsamixer I got:

No protocol specified
xcb_connection_has_error() returned true

and  set the master volume, but each time I close it and open again the master volume is returned to 0.

**Comment by chavezmx** [comment]
weird, testing the sound card directly with:
 cat /dev/urandom | aplay

I get sound from the speakers ...

maybe there is a problem with pulse audio ... ?

**Comment by chavezmx** [comment]
Finally the sound is working, for some reason the sink device for the sound card was not added dynamically, so I had to add the following lines to /etc/pulse/default.pa

load-module module-alsa-sink device=hw:0,0

and after that the sound is working.

**Comment by raphael** [comment]
good to know, thanks for sharing.

**Comment by cowlicks** [comment]
I'm also on debian 8 and the sound is not working. I'm not sure what to do from your comments to enable sound.

**Comment by chavezmx** [comment]
Just add this line to /etc/pulse/default.pa

load-module module-alsa-sink device=hw:0,0
