### ISSUE TITLE
Unable to use ethernet adapter

### ISSUE THREAD

**Issue by colemickens** [raphael/linux-4.1-samus#14]
On tsowell's patches, I was able to use my ethernet usb adapter.

Now, with linux-4.1-samus, it is detected with libusb, but dmesg doesn't show an attempt to utilize it and it doesn't appear as a new networking device.

Under linux-samus, I got:

```
$ lsusb
...
Bus 001 Device 002: ID 0fe6:9700 Kontron (Industrial Computer Source / ICS Advent) DM9601 Fast Ethernet Adapter
...

$ dmesg
...
[  135.341069] usb 1-2: USB disconnect, device number 2
[  135.341212] dm9601 1-2:1.0 enp0s20u2: unregister 'dm9601' usb-0000:00:14.0-2, Davicom DM96xx USB 10/100 Ethernet
[  137.325641] usb 1-2: new full-speed USB device number 5 using xhci_hcd
[  137.514128] dm9601 1-2:1.0 eth0: register 'dm9601' at usb-0000:00:14.0-2, Davicom DM96xx USB 10/100 Ethernet, 00:e0:4c:53:44:58
[  137.524149] dm9601 1-2:1.0 enp0s20u2: renamed from eth0
[  137.583082] dm9601 1-2:1.0 enp0s20u2: link up, 100Mbps, full-duplex, lpa 0xFFFF
```

Under linux-4.1-samus I got:
```
$ lsusb
...
Bus 001 Device 005: ID 0fe6:9700 Kontron (Industrial Computer Source / ICS Advent) DM9601 Fast Ethernet Adapter
...

$ dmesg
...
[   88.632632] usb 1-1: USB disconnect, device number 5
[   92.268112] usb 1-1: new full-speed USB device number 6 using xhci_hcd
...
```

**Comment by raphael** [comment]
You want to enable the corresponding driver module: run `make config` in `linux/build` and enable `Device Drivers -> Network device support -> USB Network Adapters -> Davicom DM96xx based USB 10/100 ethernet devices`. Compile and install the kernel.

**Comment by raphael** [comment]
The latest release (V4.1-6) has support for this adapter (and many others) built-in.

**Comment by colemickens** [comment]
Great, thank you. I'd meant to close this!
