### ISSUE TITLE
VPN not working: modprobe: FATAL: Module ppp_generic not found

### ISSUE THREAD

**Issue by vrcod** [raphael/linux-4.1-samus#15]
@raphael I've been trying to connect to my VPN, but it seems that there's a module not enabled in ```make nconfig``` and I just can't find it's reference. The error is quite clear though:
```
modprobe: FATAL: Module ppp_generic not found
```
Any clues how to enable that?

**Comment by raphael** [comment]
I ended up creating a new release that adds support as PPP / VPN is a fairly commonly needed feature. Either grab the latest or build your own after enabling PPP in `Device drivers -> Network device support -> PPP (point-to-point protocol) support`.

**Comment by AdaRoseEdwards** [comment]
I use openconnect vpn I don't seem to be able to connect even with the new build. When I connect via the command line I get:

```
Failed to open tun device: No such device
Set up tun device failed
```

**Comment by AdaRoseEdwards** [comment]
I seem to be having a similar issue with openconnect but the new kernel did not solve the issue. THe error I get running openconnect from the command line is:

```
Failed to open tun device: No such device
Set up tun device failed
```

event though `/dev/net/tun` is present.

It works on 4.1 from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.1-unstable/ I think perhaps it is another kernel feature which needs enabling but I could not find it.

**Comment by raphael** [comment]
I ended up releasing yet a new set of packages that enable TUN and pretty much every driver / file system that could make sense. This should make the latest kernel much more generic, grab v4.1-6 while it's still hot :)

**Comment by AdaRoseEdwards** [comment]
That works really well for me. Thank you. :D
