### ISSUE TITLE
makepkg -s fails on 4.1-6 release

### ISSUE THREAD

**Issue by colemickens** [raphael/linux-4.1-samus#16]
```
$ pwd
 ~/Code/raphael/linux-4.1-samus/aur 

$ git rev-parse HEAD
fffcef62a9d32b5b98ac44fe288c443a3f6d3526

$ makepkg -s
==> Making package: linux-samus4 4.1-6 (Wed Jul  8 10:40:17 PDT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v4.1-6.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131    0   131    0     0    378      0 --:--:-- --:--:-- --:--:--   378
100  170M    0  170M    0     0  1703k      0 --:--:--  0:01:42 --:--:--  695k
  -> Found config
  -> Found linux.preset
==> Validating source files with md5sums...
    v4.1-6.tar.gz ... FAILED
    config ... FAILED
    linux.preset ... Passed
==> ERROR: One or more files did not pass the validity check!
```

**Comment by colemickens** [comment]
However, when running through yaourt (I originally installed from AUR4), it seems to be proceeding and building the kernel:

```
yaourt --aur-url https://aur4.archlinux.org -Syua
```

**Comment by colemickens** [comment]
The PKGBUILD on Aur4 seems to differ from that in the source tree on Github. Additionally, there are two different PKGBUILD files in the Github repo.

**Comment by raphael** [comment]
Good catch, looks like I'm missing a step in my release procedure ;) I've fixed the PKGUILD in aur/.

**Comment by raphael** [comment]
Also the two different PKGBUILD are intentional,  the one in aur/ is the one used to build the Aur package and downloads the source from github while the one in scripts/archlinux builds the package from the local source files.

**Comment by colemickens** [comment]
Thanks for the update and information.

Looks like there's a bad symlink in there:

```
$ git pull 
Already up-to-date.

$ git rev-parse HEAD
dd513522c30f44190549ba9407dde805e1984a4d

$ cd scripts/archlinux

$ makepkg -s

==> Making package: linux-samus4 4.1-6 (Wed Jul  8 20:54:58 PDT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> Extracting sources...
==> Starting prepare()...
/home/cole/Code/raphael/linux-4.1-samus/scripts/archlinux/PKGBUILD: line 30: cd: /home/cole/Code/raphael/linux-4.1-samus/scripts/archlinux/src/linux-patched: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```

It creates the symlink, but the symlink itself is bad.  (future executions fail with `ln: failed to create symbolic link ‘/home/cole/Code/raphael/linux-4.1-samus/scripts/archlinux/src/linux-patched’: File exists`)

**Comment by raphael** [comment]
Ah the local PKGBUILD assumes that the script "scripts/patch.sh" has been run. This script creates the "linux-patched" directory. The idea is that this PKGBUILD is meant for testing changes to the source code of the kernel (I used it extensively to test the manual changes I had to make for the kernel to build / function). I should probably add an explicit check though.

**Comment by raphael** [comment]
Tweaked the PKGBUILD to check for `linux-patches` and bail if not there (with a hopefully helpful message)

**Comment by colemickens** [comment]
Perfect, it tells me to run `scripts/patch.sh` first. Thank you for the supoort and package!
