### ISSUE TITLE
Failed to start LSB: AppArmor initialization.

### ISSUE THREAD

**Issue by recri** [raphael/linux-4.1-samus#26]
Reported in /var/log/boot.log under Ubuntu 15.04

CONFIG_DEFAULT_SECURITY_APPARMOR=y

will fix this.

**Comment by raphael** [comment]
Please give the latest release a shot, it should address this and #25.

**Comment by recri** [comment]
The 4.1.4 packages fixed this, fixed #25, and also fixed the flickering in the Ctrl-Alt-F[1-6] virtual terminals.  You're on a roll, keep it up.

**Comment by raphael** [comment]
Thanks for the help. Please keep reporting issues!
