### ISSUE TITLE
Touchscreen isn't working with the latest kernel

### ISSUE THREAD

**Issue by defunkt1721** [raphael/linux-4.1-samus#28]
Hi, 

After updating to the latest kernel, the touch capabilities of the screen have stopped.

I'm running Antergos with Gnome 3.16 if that's of any help. I installed the kernel by cloning the repo. Currently compiling from the AUR and will report with results later.
 
UPDATE: After installing from AUR, it seems like touchscreen is restored.. I don't have any idea what could have caused this.

**Comment by raphael** [comment]
strange, it's working here (installed from source). I'm going to close the issue for now, re-open if you see it happen again (with hopefully additional information).
