### ISSUE TITLE
kernel doesn't boot

### ISSUE THREAD

**Issue by vrcod** [raphael/linux-4.1-samus#3]
When I select this kernel in my grub Advanced Options it then shows
```
Loading Linux 4.1.0-rc8ph
Loading initial ramdisk...
```
and gets stuck on this.
I'm running Ubuntu 15.04 with a default disk encryption. These are the two settings I've changed in ```make nconfig``` - enabled swap and ```File Systems ---> <M> Ext4 Encryption```. Any idea what the problem could be here? If it helps, Tom's kernel (https://github.com/tsowell/linux-samus) worked fine out of the box.

**Comment by nevetas** [comment]
I don't have encryption and I don't use swap so I just left everything set to default.

I get exactly the same issue as vrcod, at boot it sticks on Loading initial ramdisk...

**Comment by raphael** [comment]
@vrcod If you were using encryption with a pre 4.1 kernel (e.g. Tom's) then I doubt you need the `Ext4 Encryption` option - this is a new feature of 4.1. I'm guessing Ubuntu is using a userspace solution such as EncFS. It's hard to troubleshoot an issue I can't easily reproduce (not using Ubuntu) but my hunch is that you probably need to update the `initramfs`. I wouldn't see this issue because the Arch Linux package does it automatically. Try something like:
```
update-initramfs -c -k 4.1.0-rc8ph+
```
https://wiki.ubuntu.com/Initramfs
http://manpages.ubuntu.com/manpages/hardy/man8/update-initramfs.8.html

**Comment by vrcod** [comment]
@raphael I ran ```sudo update-initramfs -c -k 4.1.0-rc8ph``` and this is the output:
```
update-initramfs: Generating /boot/initrd.img-4.1.0-rc8ph
WARNING: missing /lib/modules/4.1.0-rc8ph
Device driver support needs thus be built-in linux image!
depmod: ERROR: could not open directory /lib/modules/4.1.0-rc8ph: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
depmod: WARNING: could not open /tmp/mkinitramfs_cxku4L/lib/modules/4.1.0-rc8ph/modules.order: No such file or directory
depmod: WARNING: could not open /tmp/mkinitramfs_cxku4L/lib/modules/4.1.0-rc8ph/modules.builtin: No such file or directory
```
So I checked the folder ```/lib/modules``` and the error is correct, I can only see my old kernel's folder in there. Do you think ```sudo make install``` failed to copy stuff in there or is this some other problem?

**Comment by nevetas** [comment]
I get the same:

h ./arch/x86/boot/install.sh 4.1.0-rc8ph arch/x86/boot/bzImage \

        System.map "/boot"

run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.1.0-rc8ph /boot/vmlinuz-4.1.0-rc8ph

run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.1.0-rc8ph /boot/vmlinuz-4.1.0-rc8ph

update-initramfs: Generating /boot/initrd.img-4.1.0-rc8ph

WARNING: missing /lib/modules/4.1.0-rc8ph

Device driver support needs thus be built-in linux image!

depmod: ERROR: could not open directory /lib/modules/4.1.0-rc8ph: No such file or directory

depmod: FATAL: could not search modules: No such file or directory

depmod: WARNING: could not open /tmp/mkinitramfs_8lJA3g/lib/modules/4.1.0-rc8ph/modules.order: No such file or directory

depmod: WARNING: could not open /tmp/mkinitramfs_8lJA3g/lib/modules/4.1.0-rc8ph/modules.builtin: No such file or directory

run-parts: executing /etc/kernel/postinst.d/pm-utils 4.1.0-rc8ph /boot/vmlinuz-4.1.0-rc8ph

run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.1.0-rc8ph /boot/vmlinuz-4.1.0-rc8ph

run-parts: executing /etc/kernel/postinst.d/update-notifier 4.1.0-rc8ph /boot/vmlinuz-4.1.0-rc8ph

run-parts: executing /etc/kernel/postinst.d/zz-update-grub 4.1.0-rc8ph /boot/vmlinuz-4.1.0-rc8ph

**Comment by vrcod** [comment]
I think I made some progress, this questions helped: http://stackoverflow.com/questions/28644386/kernel-install-gives-missing-module-error
But now when I enter my disk encryption password it says ```cryptsetup: cryptsetup failed, bad password or options?```

**Comment by nevetas** [comment]
Thanks, that let me boot. With Tom's kernel that got keyboard backlighting & sound working, but not having much luck with those at the moment.

**Comment by raphael** [comment]
OK so `sudo make modules_install` was the missing piece? I'll add a comment in the README. 
### Sound
@nevetas  As for the sound not working what do you get if you do `lsmod | grep snd_core`? This is what you should see:
```
snd_soc_sst_bdw_rt5677_mach     7593  2 
snd_soc_sst_haswell_pcm    35153  4 snd_soc_sst_bdw_rt5677_mach
snd_soc_sst_dsp        20826  1 snd_soc_sst_haswell_pcm
snd_soc_rt5677        163345  5 snd_soc_sst_bdw_rt5677_mach
snd_soc_rl6231          1610  1 snd_soc_rt5677
snd_soc_rt5677_spi      6767  3 snd_soc_rt5677
snd_soc_core          127931  6 snd_soc_rt5677,snd_soc_rt5677_spi,snd_soc_sst_haswell_pcm,snd_soc_sst_bdw_rt5677_mach
snd_compress           10827  1 snd_soc_core
snd_pcm                70277  8 snd_soc_rt5677,snd_soc_rt5677_spi,snd_soc_core,snd_hda_codec_hdmi,snd_soc_sst_haswell_pcm,snd_hda_codec,snd_hda_intel,snd_hda_controller
snd                    54265  19 snd_soc_core,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_hda_codec,snd_hda_intel,snd_compress
regmap_i2c              2727  1 snd_soc_rt5677
dw_dmac_core           16161  2 dw_dmac,snd_soc_sst_dsp
snd_soc_sst_acpi        2847  0 
```
The module that drives the broadwell chip on the Pixel 2 is `snd_soc_sst_bdw_rt5677_mach`. Another thing would be to check what `aplay -l` returns, should be:
```
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: bdwrt5677 [bdw-rt5677], device 0: System Playback (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
If the module is loaded and the `bdwrt5677` device listed then try to see if it's muted via `alsamixer`.
### Screen backlight
You should be able to control the screen backlight via the `intel_backlight` device `/sys/class/backlight/intel_backlight`. I've added a script to the repo that leverages the device to increase or decrease the brightness (`build/brightness --increase` and `build/brightness --decrease` respectively).
### Keyboard backlight
The config wasn't enabling the keyboard backlight, I've fixed that.
### Disk Encryption
@vrcod Sorry but I'm not sure what's causing this. I don't have encryption enabled here. You could check the "Security options" and "Cryptographic API" sections of the kernel configs (enable everything) but I'm not even sure that it's a kernel issue.

**Comment by nevetas** [comment]
sudo make modules_install has fixed the booting issue - thanks!

Keyboard backlight now working - thanks!

Sound....
lsmod | grep snd_core             This returned nothing, just dropped back to a prompt.

root@pixel# lsmod | grep snd_core
root@pixel# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: bdwrt5677 [bdw-rt5677], device 0: System Playback (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by vrcod** [comment]
@raphael Noticed an error when booting regarding the encrypted disk:
```
Cannot initialize device-mapper. Is dm_mod kernel module loaded?
```

**Comment by nevetas** [comment]
Sound...

Well I managed to fix it, possibly by cheating but a fix nevertheless.

Downloaded tsowell tarball

$ cd linux-samus-ubuntu-0.2.2
$ ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi 

My speakers immediatly made a popping sound, so opened a chrome browser, started a youtube video and I could finally hear it.

As usual with the 2015 pixel sound isn't amazing, but atleast it's now there if you need it.

No idea what my little fix actually did :)

**Comment by vrcod** [comment]
@nevetas you should make a separate issue if it's not related to kernel not booting.

**Comment by nevetas** [comment]
Done

**Comment by vrcod** [comment]
So I was just digging around and also comparing the config with Tom's and found something possibly missing:
```
CONFIG_BLK_DEV_DM_BUILTIN=y
CONFIG_BLK_DEV_DM=m
```
are present in Tom's config, but not this one. Could that be the problem?

**Comment by vrcod** [comment]
OK so I went into ```make nconfig``` Device Drivers, checked ```Multiple devices driver support (RAID and LVM)``` and everything that's inside it (probably not very wise) and it cured the problem. Might be worth distilling this solution and adding it to the readme at least for the people who use LVM partitions?

**Comment by raphael** [comment]
Nice! yes I'll add a note in the README (probably a good FAQ entry).
