### ISSUE TITLE
No sound (Arch)

### ISSUE THREAD

**Issue by ethanmad** [raphael/linux-4.1-samus#30]
I'm using cc3badb on my Arch install. I have `alsa-utils` (includes `alsaucm` and `amixer`) and `pulseaudio` installed. I ran `sound.sh` and got the following output
````
Setting sound card UCM verb
Restoring alsa config
Sound setup completed successfully.
```

I noticed that the firmware did not get moved to `/lib/firmware`, so I did that myself and restarted pulseaudio. No luck. I added `load-module module-alsa-sink device=hw:0,0` to `default.pa`. Rebooted. Still no sound.

**Comment by raphael** [comment]
A few things to check in order:
1. Are the sound modules correctly loaded? (`lsmod | grep bdw` should return lines that include `snd_soc_sst_bdw_rt5677_mach`)
2. Are the sound devices properly installed? (`ls /dev/snd` should return ~15 entries, including `pcmC0D0p`, `pcmC0D1c`)
3. Does `aplay -l` list the sound card (`card 0: bdwrt5677 [bdw-rt5677], device 0: System Playback (*) []`)
4. Does `pavucontrol` show the `bdw-rt5677` device?, is it enabled (Configuration tab) and unmuted?

**Comment by ethanmad** [comment]
1. Yes
2. Yes (I counted 12 entries, don't know if that's an issue)
3. Yes
4. Yes (bdw-rt5677's profile is "Analog Stereo Output" and it's at 100% gain, unmuted). When the system expects to make sound (e.g. changing volume in pavucontrol [I'm guessing there's a ding to indicate the new volume]), the volume bar shows the sound (but I don't hear it).

When I run `$ pulseaudio`, I get some errors:
```
W: [pulseaudio] sink.c: Default and alternate sample rates are the same.
W: [pulseaudio] source.c: Default and alternate sample rates are the same.
E: [pulseaudio] module-alsa-card.c: Failed to find a working profile.
E: [pulseaudio] module.c: Failed to load module "module-alsa-card" (argument: "device_id="0" name="platform-bdw-rt5677" card_name="alsa_card.platform-bdw-rt5677" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes card_properties="module-udev-detect.discovered=1""): initialization failed.
AW: [pulseaudio] sink.c: Default and alternate sample rates are the same.
E: [alsa-sink-System Playback (*)] alsa-sink.c: Error opening PCM device hw:0: Device or resource busy
```

The third and fourth lines appear to me to be important.

**Comment by raphael** [comment]
These errors seem to point to something wrong with the pulseaudio configuration. Do you have a `~/.pulse` file? if so try to remove it. If that doesn't help paste in your `/etc/pulse/default.pa`.

**Comment by ethanmad** [comment]
I don't have  `~/.pulse`.

`/etc/pulse/default.pa`:
``` ruby
#!/usr/bin/pulseaudio -nF
#
# This file is part of PulseAudio.
#
# PulseAudio is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# PulseAudio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.

# This startup script is used only if PulseAudio is started per-user
# (i.e. not in system mode)

.nofail

### Load something into the sample cache
#load-sample-lazy x11-bell /usr/share/sounds/freedesktop/stereo/bell.oga
#load-sample-lazy pulse-hotplug /usr/share/sounds/freedesktop/stereo/device-added.oga
#load-sample-lazy pulse-coldplug /usr/share/sounds/freedesktop/stereo/device-added.oga
#load-sample-lazy pulse-access /usr/share/sounds/freedesktop/stereo/message.oga

.fail

### Automatically restore the volume of streams and devices
load-module module-device-restore
load-module module-stream-restore
load-module module-card-restore

### Automatically augment property information from .desktop files
### stored in /usr/share/application
load-module module-augment-properties

### Should be after module-*-restore but before module-*-detect
load-module module-switch-on-port-available

### Load audio drivers statically
### (it's probably better to not load these drivers manually, but instead
### use module-udev-detect -- see below -- for doing this automatically)
load-module module-alsa-sink device=hw:0,0
#load-module module-alsa-source device=hw:1,0
#load-module module-oss device="/dev/dsp" sink_name=output source_name=input
#load-module module-oss-mmap device="/dev/dsp" sink_name=output source_name=input
#load-module module-null-sink
#load-module module-pipe-sink

### Automatically load driver modules depending on the hardware available
.ifexists module-udev-detect.so
load-module module-alsa-source device=hw:0,1
load-module module-alsa-source device=hw:0,2
load-module module-udev-detect
.else
### Use the static hardware detection module (for systems that lack udev support)
load-module module-detect
.endif

### Automatically connect sink and source if JACK server is present
.ifexists module-jackdbus-detect.so
.nofail
load-module module-jackdbus-detect channels=2
.fail
.endif

### Automatically load driver modules for Bluetooth hardware
.ifexists module-bluetooth-policy.so
load-module module-bluetooth-policy
.endif

.ifexists module-bluetooth-discover.so
load-module module-bluetooth-discover
.endif

### Load several protocols
.ifexists module-esound-protocol-unix.so
load-module module-esound-protocol-unix
.endif
load-module module-native-protocol-unix

### Network access (may be configured with paprefs, so leave this commented
### here if you plan to use paprefs)
#load-module module-esound-protocol-tcp
#load-module module-native-protocol-tcp
#load-module module-zeroconf-publish

### Load the RTP receiver module (also configured via paprefs, see above)
#load-module module-rtp-recv

### Load the RTP sender module (also configured via paprefs, see above)
#load-module module-null-sink sink_name=rtp format=s16be channels=2 rate=44100 sink_properties="device.description='RTP Multicast Sink'"
#load-module module-rtp-send source=rtp.monitor

### Load additional modules from GConf settings. This can be configured with the paprefs tool.
### Please keep in mind that the modules configured by paprefs might conflict with manually
### loaded modules.
.ifexists module-gconf.so
.nofail
load-module module-gconf
.fail
.endif

### Automatically restore the default sink/source when changed by the user
### during runtime
### NOTE: This should be loaded as early as possible so that subsequent modules
### that look up the default sink/source get the right value
load-module module-default-device-restore

### Automatically move streams to the default sink if the sink they are
### connected to dies, similar for sources
load-module module-rescue-streams

### Make sure we always have a sink around, even if it is a null sink.
load-module module-always-sink

### Honour intended role device property
load-module module-intended-roles

### Automatically suspend sinks/sources that become idle for too long
load-module module-suspend-on-idle

### If autoexit on idle is enabled we want to make sure we only quit
### when no local session needs us anymore.
.ifexists module-console-kit.so
load-module module-console-kit
.endif
.ifexists module-systemd-login.so
load-module module-systemd-login
.endif

### Enable positioned event sounds
load-module module-position-event-sounds

### Cork music/video streams when a phone stream is active
load-module module-role-cork

### Modules to allow autoloading of filters (such as echo cancellation)
### on demand. module-filter-heuristics tries to determine what filters
### make sense, and module-filter-apply does the heavy-lifting of
### loading modules and rerouting streams.
load-module module-filter-heuristics
load-module module-filter-apply

# X11 modules should not be started from default.pa so that one daemon
# can be shared by multiple sessions.

### Load X11 bell module
#load-module module-x11-bell sample=x11-bell

### Register ourselves in the X11 session manager
#load-module module-x11-xsmp

### Publish connection data in the X11 root window
#.ifexists module-x11-publish.so
#.nofail
#load-module module-x11-publish
#.fail
#.endif

### Make some devices default
#set-default-sink output
#set-default-source input
```

**Comment by raphael** [comment]
Not seeing anything obviously wrong with it. You could check that the broadwell sound card is indeed card 0 as you specify with `load-module module-alsa-sink device=hw:0,0` (you can do that with `aplay -l`). The other thing would be to check that you have the `udev` alsa module:
```
find / -name module-udev-detect.so 2>/dev/null
/usr/lib/pulse-6.0/modules/module-udev-detect.so
```
If both these check out I'm out of ideas...

**Comment by ethanmad** [comment]
`aplay -l` shows `card 0: bdwrt6577 [bdw-rt5677], device 0: System Playback (*) []`.

The `find` command you listed shows exactly the same output.

Any way to start from scratch? Maybe I did something wrong along the way. Also possibly worth mentioning I'm not using a desktop environment, just i3-wm.

**Comment by raphael** [comment]
You could try reinstalling pulseaudio but that seems like a long shot. You could also check `alsamixer` and make sure nothing is muted in there (you want `OO` and not `MM` under each item). Also check whether headphones work. Grasping at straws...

**Comment by ethanmad** [comment]
:facepunch: :arrow_forward: :dizzy_face: My speakers were muted... So embarrassing. :sob: 

I had previously unmuted speakers and set the Master volume to 100, but it looks like every time I open alsamixer, the volume is set to 0 and every time I reboot the speakers are muted. I'll look into fixing that.

So now that sound is working, would you recommend using the AUR package or using the git repo? With the AUR package, do I have to rerun the install script when it gets updated?

Sorry for wasting your time on this and thank you so much for the help!

**Comment by raphael** [comment]
glad you found it! In terms of installation the advantage of using the package is that you'll see when new versions are available without having to check the github repo. As far as having to re-run the scripts, no that shouldn't be the case in general. Only if new scripts get added that enable new stuff would you need to run these.

**Comment by ethanmad** [comment]
And it's safe to install the AUR version after installing the git version?
Where can I find the `linux-4.1-samus` folder after installing from the AUR?

Thanks again for the help and work you've put in on this kernel.

**Comment by raphael** [comment]
Yeah it's safe to switch from AUR to git and vice versa. By default the downloaded source is deleted by `yaourt` after the kernel is compiled - there's probably an option to disable that. 

BTW there is an annoying behavior where because there are actually 3 packages defined in the PKGBUILD (kernel, headers and docs) `yaourt` ends up downloading and compiling the kernel 3 times. `yaourt` will prompt each time whether you want to install all 3 packages at once but replying yes doesn't prevent it from proceeding. So the trick is to say yes the first time and then say no when it asks whether to install the next 2 packages...

**Comment by genkimarshall** [comment]
Learned that the hard way ^. A quick search and I couldn't find people with similar complaints.

Maybe my Google-Fu is off, have you seen anyone else with this issue with how it handles the PKGBUILD?

**Comment by ethanmad** [comment]
I moved from `yaourt` to [`pacaur`](https://wiki.archlinux.org/index.php/Pacaur), but I think it also deletes the directory. I have the git repo anyway. 

That second paragraph explains why it took so long (more than 30 minutes) to install the package. Are the other two packages not necessary? If not, why are they in the PKGBUILD?

**Comment by raphael** [comment]
I based my PKGBUILD on the official [Arch Linux linux kernel](https://projects.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/linux) PKGBUILD. I have seen that behavior with other packages (vte3-notification comes to mind). dunno, maybe I'm missing something...

**Comment by ethanmad** [comment]
Actually, it seems like pacaur handles it correctly. It only gets the one package as far as I can tell.

**Comment by raphael** [comment]
good to know.... will give it a shot.
