### ISSUE TITLE
enable-brightness.sh not found

### ISSUE THREAD

**Issue by Popog** [raphael/linux-4.1-samus#31]
`script/setup/enable-brightness.service` references `/usr/local/bin/enable-brightness.sh`, which does not appear to exist.

**Comment by ethanmad** [comment]
:+1: Not there for me either.

**Comment by agaskell** [comment]
I use [xbacklight](https://www.archlinux.org/packages/?name=xorg-xbacklight) and it works well. If you happen to use i3 here are the bindings:
```
bindsym F7 exec xbacklight -inc 12.5
bindsym F6 exec xbacklight -dec 12.5
```

**Comment by ethanmad** [comment]
@agaskell Interesting that you use i3 to manage those bindings. Any advantages of putting them in ~/.i3/config rather than using xbindkeys?

**Comment by agaskell** [comment]
@ethanmad I don't think there's an advantage. I'm always in i3 and it works :)

**Comment by ethanmad** [comment]
@agaskell Maybe I'll put other bindings there so I don't need xbindkeys. I've never thought about it.

**Comment by raphael** [comment]
Thanks, I added the script.
