### ISSUE TITLE
i915 DRM Bug

### ISSUE THREAD

**Issue by roobyz** [raphael/linux-4.1-samus#32]
Hi raphael,

Thanks for the lovely work you've been doing on the kernel.  So far most everything is working well.

I've encountered an interesting kernel (4.1.5ph+) bug after getting a 4K monitor (Dell P2715Q A02 connected with the Google USB-C Displayport cable).  When set to 4K/60Hz resolution everything seems to work fine, however on random occasions, I am get the following error message (dmesg) and my screen goes blank:

>
[13295.335556] [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun

The interesting thing is that the error seems to be triggered when:
* using Chrome browser.  
* using Firefox on some web-pages (i.e. http://synchronybank.com/): By closing or switching tabs or minimizing Firefox, the screen comes back.  
* when R-Studio finishes loading. 

It almost seems like specific set or type of HTML triggers a kernel Displayport bug when the monitor resolution is set to 4K.  Weird right?

Cheers,
Roberto

**Comment by raphael** [comment]
There are reports in the wild of this error happening but as far as I know no fix yet. One thing you could try to play with is the acceleration method. The `xaccel.sh` script in this repo sets the method to "glamor" (the most recent one). You could try setting it to "sna" or "uxa" instead and see if that makes a difference (edit `/etc/X11/xorg.conf.d` or `/usr/share/X11/xorg.conf.d` depending on the distro).

**Comment by roobyz** [comment]
Good suggestion.  UXA had atrocious performance and SNA and glamor performed best, however neither option resolved the issue.

**Comment by raphael** [comment]
Could you try with the generic kernel and check whether that problem happens with it as well?

**Comment by roobyz** [comment]
After much searching I figured it out!  The [arch wiki](https://wiki.archlinux.org/index.php/Intel_graphics) had a note on a kernel regression that will be resolved in the 4.2 release:

>
**Loss of horizontal sync when switching TTYs**
A regression is present in kernels 3.19.3+ (and possibly older kernels as well) that results in horizontal sync loss on Broadwell machines when switching TTYs. [6] To fix it, you can add ***i915.enable_ips=0*** to your kernel command-line as a workaround, or if you're running 4.1, you can rebuild your kernel with the patch available here. The fix was merged into the mainline kernel in 4.2-rc1. 

It doesn't explicitly call out my example, but definitely solves the issue.  Apparently you could add the patch to your kernel.  Thanks for the help!

**Comment by raphael** [comment]
Thanks for looking into it. The link to the patch seems broken, I'll add a note to the README for now.

**Comment by raphael** [comment]
I've just released v4.2-1 which runs the 4.2 kernel. Could you confirm that the bug is fixed there? (i.e. you don't need to disable IPS anymore)

**Comment by roobyz** [comment]
Thanks for the update and excellent question. I checked whether 4.2 resolved my bug, but it does NOT. I'm wondering whether related bugs were resolved but not mine. Like I mentioned earlier, the fix didn't "explicitly call out my example".  However, the IPS disable continues to work as before. :)
