### ISSUE TITLE
Module `vboxdrv`  not found.

### ISSUE THREAD

**Issue by genkimarshall** [raphael/linux-4.1-samus#35]
Hello, I am attempting to set up VirtualBox on my machine, but I am encountering this.
```shell
# modprobe vboxdrv
modprobe: FATAL: Module vboxdrv not found.
```
So, when starting virtualbox, I get:
```
$ virtualbox
WARNING: The vboxdrv kernel module is not loaded. Either there is no module 
available for the current kernel (4.1.5-12ph) or it failed to
load. Please reinstall the kernel module virtualbox-host-modules or
if you don't use our stock kernel compile the modules with

sudo dkms autoinstall

You will not be able to start VMs until this problem is fixed.
VirtualBox: supR3HardenedMainGetTrustedMain:
dlopen("/usr/lib/virtualbox/VirtualBox.so",) failed:
libQtCore.so.4: cannot open shared object file: No such file or directory.
```

Currently on release `4.1-12`.
I have spent some time looking this up but nothing seems applicable. They often refer to logs / steps that are very Ubuntu-specific. None seem to be particularly relevant. I also vaguely seem to remember reading that virtualization on the CB Pixel on Linux might run into some issues, but now I can't find the source. This makes me think the issue is platform-specific, but please tell me if you think that is not the case.
I found [this](http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/running-virtual-machines-on-your-chromebook), but I thought I should bring it up here before attempting that.
Unfortunately, classes are about to start and I am a little more paranoid than usual about messing my machine up.
Thanks so much for your time and work thus far on making this custom kernel. I thought I would report early, and if the solution is not clear right away, I will of course continue to look this up on my own.

**Comment by raphael** [comment]
I have VirtualBox running just fine. The error above seems to indicate that you need to install libQtCore.so - probably part of the Qt package of your distro.

**Comment by genkimarshall** [comment]
You're totally right, I missed that `qt4` was an optional dependency in the package I used for virtualbox.
Seems I was led astray by a bad memory that something was wrong at a lower level.
Sorry for your time, and thanks so much for the help!

**Comment by genkimarshall** [comment]
Just in case anyone happens to come across this in the future, to get it all working ended up being a bit more involved.
Just see the last comment in this thread [0] for a full solution.

[0]: https://bbs.archlinux.org/viewtopic.php?id=188251
