### ISSUE TITLE
Sound not Working

### ISSUE THREAD

**Issue by nevetas** [raphael/linux-4.1-samus#4]
lsmod | grep snd_core This returned nothing, just dropped back to a prompt.

root@pixel# lsmod | grep snd_core
root@pixel# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
Subdevices: 1/1
Subdevice #0: subdevice #0
card 1: bdwrt5677 [bdw-rt5677], device 0: System Playback (*) []
Subdevices: 0/1
Subdevice #0: subdevice #0

I tried some other outputs if any of this helps?

find / -name snd_soc_sst_bdw_rt5677_mach
/sys/module/snd_soc_rt5677/holders/snd_soc_sst_bdw_rt5677_mach
/sys/module/snd_soc_core/holders/snd_soc_sst_bdw_rt5677_mach
/sys/module/snd_soc_sst_haswell_pcm/holders/snd_soc_sst_bdw_rt5677_mach
/sys/module/snd_soc_sst_bdw_rt5677_mach

lsmod | grep snd_soc_core
snd_soc_core 127971 6 snd_soc_rt5677,snd_soc_rt5677_spi,snd_soc_sst_haswell_pcm,snd_soc_sst_bdw_rt5677_mach
snd_compress 10891 1 snd_soc_core
snd_pcm 70533 10 snd_soc_rt5677,snd_pcm_oss,snd_soc_rt5677_spi,snd_soc_core,snd_hda_codec_hdmi,snd_soc_sst_haswell_pcm,snd_hda_codec,snd_hda_intel,snd_hda_controller
snd 54617 20 snd_pcm_oss,snd_soc_core,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_seq,snd_rawmidi,snd_hda_codec,snd_hda_intel,snd_seq_oss,snd_seq_device,snd_compress,snd_mixer_oss

alsamixer has master:100% Headphone(can't click enter on this) Speaker (can't click enter on this) and sidetone:100%

I paired some bluetooth headphones, which does give me sound, so using them for now.

**Comment by nevetas** [comment]
Well I managed to fix it, possibly by cheating but a fix nevertheless.

Downloaded tsowell tarball

$ cd linux-samus-ubuntu-0.2.2
$ ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi

My speakers immediatly made a popping sound, so opened a chrome browser, started a youtube video and I could finally hear it.

As usual with the 2015 pixel sound isn't amazing, but atleast it's now there if you need it.

No idea what my little fix actually did :)

**Comment by raphael** [comment]
Ah yes that's it, I'll update the README.
