### ISSUE TITLE
Microphone is not working

### ISSUE THREAD

**Issue by vrcod** [raphael/linux-4.1-samus#5]
I followed the instructions of editing ```/etc/pulse/default.pa``` and now I can see the microphone in ```pavucontrol``` as bdw-rt5677, but it doesn't work. Not sure if this is OS specific (I'm on Ubuntu 15.04) or if it's still a kernel issue. By the way, the situation is exactly the same with Tom's kernel too.

**Comment by raphael** [comment]
Try running `amixer -c1 set Mic 0DB`. I also uploaded a `sounds.sh` script that makes the various tweaks to make sound work (you probably already have made them though).

**Comment by nevetas** [comment]
The sounds.sh script killed my sound on a 4.1 build. I had to go in a re-name the modified file back, reboot and sound worked OK again. I'd rather have sound then a microphone so just ran the standard command on the next build rather then the script.

**Comment by raphael** [comment]
That can happen if the mic hardware is already listed and the script adds it again then PulseAudio won't even load. The script tries to detect that case but it's far from perfect. Can you see the mic in your sound settings? if so just running the command above should make it work.

**Comment by vrcod** [comment]
@raphael So I ran ```amixer -c1 set Mic 0DB``` as you suggested, this is the output:
```
Simple mixer control 'Mic',0
  Capabilities: cvolume
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 31
  Front Left: Capture 0 [0%] [-99999.99dB]
  Front Right: Capture 0 [0%] [-99999.99dB]
```
but that didn't change anything. bdw-rt5677 shows as an input device, but it's completely dead. I'm just wondering, did anyone actually get the microphone working on any distro?
This is what ```arecord -l``` produces by the way, does this look ok?
```
**** List of CAPTURE Hardware Devices ****
card 1: bdwrt5677 [bdw-rt5677], device 1: Capture (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: bdwrt5677 [bdw-rt5677], device 2: Wake on Voice rt5677-dspbuffer-2 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by raphael-rs** [comment]
The mic is working fine for me (using Arch Linux - not sure that's relevant though). I guess you made sure it wasn't muted in PulseAudio? Using this I can record and replay:
```
arecord -d 10 /tmp/test-mic.wav
aplay /tmp/test-mic.wav
```

**Comment by Ivan0xFF** [comment]
This is what I get when adding those two lines to my /etc/pulse/default.pa

    E: [pulseaudio] module.c: Failed to load module "module-alsa-source" (argument: "device=hw:1,1"): initialization failed.
    E: [pulseaudio] main.c: Module load failed.
    E: [pulseaudio] main.c: Failed to initialize daemon.

**Comment by raphael** [comment]
@Ivan0xFF what does `arecord -l` return?

**Comment by raphael** [comment]
@vrcod did you ever get the mic to work? I did push some fixes in that area lately - might want to try with the latest: get the latest kernel sources, build and install it, reboot then run the latest `sound.sh` script (in `scripts/setup`).

**Comment by vrcod** [comment]
@raphael Thanks a lot. I've just recompiled the kernel with your new changes, ran sound.sh and now the mic works. The quality of recording is really bad though - a lot of static noise, not sure what the cause of that is, how do your tests sound like? Another observation - it now shows to same mic devices in pulseaudio, I'm guessing that's because there's a microphone array (2 microphones) and the driver is not sophisticated enough to merge them into one?

**Comment by raphael** [comment]
Try to lower the mic volume in alsa so it picks up less noise, for example `amixer -c1 set Mic -10DB`. I haven't run extensive tests with it yet, let me know if that helps. There are actually two different mics on the pixel, my reading of the code is that the second mic is dedicated to the "OK Google" feature (wake-on-stream) - I could be wrong though.

**Comment by vrcod** [comment]
@raphael Actually, ```amixer -c1 set Mic -10DB``` produces an error
```
amixer: invalid option -- '1'
Invalid switch or option needs an argument.
amixer: invalid option -- '0'
Invalid switch or option needs an argument.
```
I'm digging through alsamixer docs, but can't find anything similar to this. So far what I've noticed is that one of the mics doesn't work, but I'm not concerned about that, I only need one.
Do you know what are the names of microphones in ```alsamixer``` "GUI"? Is it ```DAC1 MIXL DAC1``` and ```DAC1 MIXR DAC1```? There's like a hundred things in there, can't make anything out of it.

**Comment by raphael** [comment]
Ah try using percentages instead for example `amixer -c1 set Mic "60%"`. In alsamixer if you select the "bdw-rt5677" card and "Capture" it's the "Mic" control.

**Comment by raphael** [comment]
Closing for now - open a new issue with specifics if needed.

**Comment by genkimarshall** [comment]
Just switched over to your configuration from tsowell's, and it seems all is working well, except I am having trouble with the microphone. I am able to successfully use `arecord` and `aplay` to record through the mic and then play it back. Unfortunately, websites like Google Hangouts say:
> Hangouts doesn't detect a microphone connected to your computer.

I have done some looking online. It doesn't seem I'm finding people with the same issue, but I wanted to ask if anyone else has experienced this before digging further.

**Comment by raphael** [comment]
Sounds like a pulseaudio issue. Is pulseaudio running? What does `pulseaudio` return?

**Comment by genkimarshall** [comment]
Ah, well that was certainly silly of me. Sorry, I had never used `pulseaudio` before, instead just using `alsa`. Forgot to start it on my startup, using `pulseaudio -D &` in my `.xinitrc` now. My browser detects it now, so that's great. I also tested it with another person, and they can hear my voice through it.
However now, my audio isn't working though. After originally installing `pulseaudio` and realizing the microphone wasn't working, I uninstalled `pulseaudio` and went back to using just `alsa` like I had before and the audio was working just fine. Now with `pulseaudio` set back up and configured, it seems sound is no longer working. I am very inexperienced with `pulseaudio` so not sure. I did notice a couple funny things though.
- Despire having `load-module module-alsa-sink device=hw:0,0` in my `/etc/pulse/default.pa`, `pactl info` says: `Default Sink: alsa_output.pci-0000_00_03.0.hdmi-stereo`. That doesn't seem right.
- `alsamixer` now has the interface showing controls for `PulseAudio` as the Card/Chip. I guess that's what it's supposed to do? Modifying these levels (one for `Master`, one for `Capture`) gives no success. I can manually select the `bdw-rt5677` as the sound card, which brings up the controls like I used to have them, but once again, no sound.

Sorry to give more trouble. Please let me know if I need to CP output from anything. If you're not sure, I'll take the time to dig deeper into this myself.

**Comment by raphael** [comment]
You want the default sink to be the card, this is independent of forcing the module to load. You could run `pavucontrol` and from the `Output Devices` select the card as "fallback device". You could also make sure that the volume for the card is not zero and that it is not muted.

**Comment by genkimarshall** [comment]
Great! Installing `pavucontrol` and setting the output as default, along with setting it to use default Headphones (seems the old method of auto-switching didn't apply) has solved the problem. Am successfully able to make video calls, speak through the mic, listen to audio, etc. Thanks so much for your time!

**Comment by raphael** [comment]
Glad to hear things are working!
