### ISSUE TITLE
Xorg hangs after several secs

### ISSUE THREAD

**Issue by antonl1911** [raphael/linux-4.1-samus#6]
I have regular Pixel 2015 and Arch linux installed on internal SSD. Tsowell kernel works OK, but with this kernel Xorg hangs within 10 seconds of starting it. What can be the source of this problem?

**Comment by raphael** [comment]
Maybe a needed module is not compiled? The config in this repo doesn't enable every single possible module so it doesn't take hours to compile (and is marginally more efficient). Maybe `/var/log/Xorg.0.log` gives you a clue? You could also diff the `.config` in `build/linux` with the one from Tom.

**Comment by antonl1911** [comment]
What's interesting is that under root user hang doesn't happen.

**Comment by raphael** [comment]
Do you have a `~/.xinitrc` file? which DE are you using? I'd look into any startup script (gnome start applications etc.)

**Comment by antonl1911** [comment]
You're right, starting without ~/.xinitr succeeded. Then I type "awesome" in one of terminals and freeze happens again.

**Comment by raphael** [comment]
Did you ever figure it out? if not what's the content of your `~/.xinitrc` file?

**Comment by raphael** [comment]
Closing for now - re-open if needed.

**Comment by antonl1911** [comment]
Finally enabled ssh to trace this down, after starting awesome, I have this in dmesg:
    [   66.720176] BUG: unable to handle kernel NULL pointer dereference at           (null)
[   66.724588] IP: [<          (null)>]           (null)
[   66.728972] PGD 274705067 PUD 274abe067 PMD 0 
[   66.733369] Oops: 0010 [#1] SMP 
[   66.737772] Modules linked in: ctr ccm uvcvideo btusb videobuf2_vmalloc btbcm videobuf2_memops btintel videobuf2_core bluetooth v4l2_common videodev media arc4 snd_soc_sst_bdw_rt5677_mach mousedev snd_soc_sst_haswell_pcm snd_soc_sst_dsp coretemp hwmon iTCO_wdt intel_rapl iosf_mbi x86_pkg_temp_thermal intel_powerclamp crc32_pclmul crc32c_intel aesni_intel iwlmvm aes_x86_64 glue_helper lrw gf128mul mac80211 ablk_helper cryptd pcspkr snd_hda_codec_hdmi iwlwifi cfg80211 snd_hda_intel snd_soc_rt5677 rfkill snd_hda_controller snd_soc_rl6231 snd_soc_rt5677_spi thermal snd_hda_codec snd_soc_core tpm_tis snd_hwdep tpm snd_hda_core snd_compress battery snd_pcm gpio_lynxpoint ac snd_timer atmel_mxt_ts 8250_dw uas snd evdev soundcore usb_storage dw_dmac processor snd_soc_sst_acpi i2c_designware_platform dw_dmac_core
[   66.761776]  lpc_ich i2c_designware_core spi_pxa2xx_platform leds_chromeos_keyboard sch_fq_codel ip_tables x_tables ext4 mbcache jbd2 sd_mod atkbd libps2 ahci libahci libata xhci_pci xhci_hcd scsi_mod usbcore usb_common i8042 serio sdhci_acpi sdhci led_class mmc_core i915 button intel_gtt i2c_algo_bit video drm_kms_helper drm
[   66.776716] CPU: 1 PID: 604 Comm: Xorg Tainted: G     U          4.1.0ph+ #3
[   66.781784] Hardware name: GOOGLE Samus, BIOS          04/02/2015
[   66.786788] task: ffff880274bfa8a0 ti: ffff880274920000 task.ti: ffff880274920000
[   66.791861] RIP: 0010:[<0000000000000000>]  [<          (null)>]           (null)
[   66.796963] RSP: 0018:ffff880274923b60  EFLAGS: 00010246
[   66.801950] RAX: 0000000000000000 RBX: ffff88026d394000 RCX: ffff880077407700
[   66.806446] RDX: 00000000fffff04a RSI: ffff8802747c1958 RDI: ffff8802747c3d38
[   66.811274] RBP: ffff880274923b98 R08: ffff880274923dc8 R09: ffff88026c9af480
[   66.816060] R10: ffff8800782fd800 R11: 00000000000000c0 R12: ffff8802747c3d38
[   66.820767] R13: ffff8802747c1958 R14: 00000000fffff04a R15: ffff8802747c195c
[   66.825312] FS:  00007fe329ab6940(0000) GS:ffff88027ec80000(0000) knlGS:0000000000000000
[   66.829796] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   66.834172] CR2: 0000000000000000 CR3: 000000027359b000 CR4: 00000000001407e0
[   66.838626] Stack:
[   66.843028]  ffffffffa00c8b8a ffff880274923b78 0000000000000001 ffff8802747c3d38
[   66.847423]  ffff880274679900 ffff88026d394000 ffff88026c9af480 ffff880274923c18
[   66.851733]  ffffffffa00df994 ffff880273449d00 ffff8802747c3d38 ffff8800782fd800
[   66.855892] Call Trace:
[   66.859934]  [<ffffffffa00c8b8a>] ? i915_gem_object_sync+0xda/0x110 [i915]
[   66.864100]  [<ffffffffa00df994>] intel_execlists_submission+0x294/0x4e0 [i915]
[   66.868258]  [<ffffffffa00bee83>] i915_gem_do_execbuffer.isra.13+0xa43/0x1190 [i915]
[   66.872317]  [<ffffffff811ec311>] ? idr_alloc+0x81/0xf0
[   66.876249]  [<ffffffffa001e904>] ? drm_vma_node_allow+0xa4/0xd0 [drm]
[   66.880276]  [<ffffffffa00c8352>] ? i915_gem_retire_requests_ring+0x112/0x180 [i915]
[   66.884321]  [<ffffffff814189c1>] ? mutex_lock_interruptible+0x11/0x50
[   66.888388]  [<ffffffffa00c08c1>] i915_gem_execbuffer2+0x141/0x2b0 [i915]
[   66.892502]  [<ffffffffa00057cb>] drm_ioctl+0x11b/0x600 [drm]
[   66.896571]  [<ffffffffa00c0780>] ? i915_gem_execbuffer+0x430/0x430 [i915]
[   66.900155]  [<ffffffff81137b16>] do_vfs_ioctl+0x2a6/0x4b0
[   66.903559]  [<ffffffff8131f431>] ? __sys_recvmsg+0x61/0x80
[   66.907456]  [<ffffffff81137d5c>] SyS_ioctl+0x3c/0x80
[   66.911318]  [<ffffffff8141ad9b>] system_call_fastpath+0x16/0x6e
[   66.915195] Code:  Bad RIP value.
[   66.919078] RIP  [<          (null)>]           (null)
[   66.922933]  RSP <ffff880274923b60>
[   66.926748] CR2: 0000000000000000
[   66.946975] ---[ end trace 8e45a58857f040bc ]---

**Comment by antonl1911** [comment]
https://wiki.archlinux.org/index.php/Intel_graphics#Kernel_crashing_w.2Fkernels_4.0.2B_on_Broadwell.2FCore-M_chips
