### ISSUE TITLE
Upgrade to 4.1 final release

### ISSUE THREAD

**Issue by vrcod** [raphael/linux-4.1-samus#7]
So 4.1 just came out, I'm guessing replacing current rc8 should be easy?

**Comment by nevetas** [comment]
I'll try and compile using the scripts. presume this is the 4.1 to use?

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.1-unstable/

**Comment by nevetas** [comment]
Worked fine using the scripts, remove rc8 from build.sh

**Comment by raphael** [comment]
Yes that should work just fine, I changed the default and uploaded the build files to the repo as well.
