### ISSUE TITLE
uname shows 4.1.0-rc8ph on new official 4.1 build

### ISSUE THREAD

**Issue by nevetas** [raphael/linux-4.1-samus#8]
Just did a new build with the newly updated .zip (4.1).

All went fine, but a uname -a shows:

4.1.0-rc8ph

?

**Comment by raphael-rs** [comment]
Bah I had not pushed `build/linux`... Also I rewrote the history to use my personal email. So do a `git fetch` followed by `git checkout master && git reset --hard origin/master` to retrieve the latest.

**Comment by raphael** [comment]
Bah I had not pushed build/linux... Also I rewrote the history to use my personal email. So do a git fetch followed by git checkout master && git reset --hard origin/master to retrieve the latest.

**Comment by nevetas** [comment]
Thanks I will try again

**Comment by nevetas** [comment]
Works fine now thanks!
