### ISSUE TITLE
nconfig error

### ISSUE THREAD

**Issue by SimionKreimer** [raphael/linux-4.1-samus#9]
Hi, I'm running Mint 17.1 Cinnamon on my Pixel 2015 LS and I've updated my kernel to 4.1. I've had good luck with the Sowell patch, but I couldn't get my mic and camera to work so I was hoping this would help.  When I try to run nconfig I always seem to get this error:
make nconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/nconf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTCC  scripts/kconfig/nconf.gui.o
  HOSTLD  scripts/kconfig/nconf
scripts/kconfig/nconf  Kconfig
drivers/net/ethernet/Kconfig:136: can't open file "drivers/net/ethernet/nvidia/Kconfig"
make[1]: *** [nconfig] Error 1
make: *** [nconfig] Error 2
How do I get around this? Sorry if I'm missing something obvious, I'm a bit of a newb.

Thanks, Simion

**Comment by raphael** [comment]
Where are you running `make nconfig`? from the `build/linux` directory?

**Comment by SimionKreimer** [comment]
Yes I'm running it from the build/linux directory. Let me give it a shot with the update.

**Comment by raphael** [comment]
That should work, closing for now - reopen if needed.
